ARG PLAYWRIGHT_VERSION
FROM mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-noble

WORKDIR /app

ARG PLAYWRIGHT_VERSION
RUN npm install --ignore-scripts @playwright/test@${PLAYWRIGHT_VERSION}

COPY playwright.config.ts tsconfig.base.json ./
COPY e2e/ ./e2e/

CMD ["npx", "playwright", "test", "--config=playwright.config.ts"]
